# Site settings
title: Thomas Jensen
email: jensen.thomas.howard@gmail.com
description: > # keep this and put description below
  Programmer and Game Developer
  Skills: Data Structures & Algorithms, PCG, UI, Tools
url: "https://thomasjensen.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/gamingportfolio"
github_username: hrimfisk
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
